# This file was generated by GoReleaser. DO NOT EDIT.
cask "wp-ops" do
  binary "wp-ops", target: "trellis-ops"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/wp-ops"]
    end
  end

  version "5.24.5"

  on_macos do
    on_arm do
      sha256 "4b8cde193ae648967cf2bae14708c75b91968aa4754e996436524980735a9fc0"
      url "https://github.com/imagewize/wp-ops/releases/download/v#{version}/wp-ops_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4a0d4b97d73379e6114076c52024f07fe45a2cd954028eeb2d926695d97453b5"
      url "https://github.com/imagewize/wp-ops/releases/download/v#{version}/wp-ops_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6a93d8238d0119591debe35744a034c298779ef0490dce4b168386a8ff8e3e1b"
      url "https://github.com/imagewize/wp-ops/releases/download/v#{version}/wp-ops_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "77e59795403e26660efe9afebaedf4dfb42b1cc3f28c2933c330cfb99d878692"
      url "https://github.com/imagewize/wp-ops/releases/download/v#{version}/wp-ops_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wp-ops"
  desc "Unified CLI for WordPress operations, Trellis, and Bedrock workflows"
  homepage "https://github.com/imagewize/wp-ops"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wp-ops"

  # No zap stanza required
end
