# This file was generated by GoReleaser. DO NOT EDIT.
cask "wp-ops" do
  version "3.30.0"

  on_macos do
    on_intel do
      sha256 "9ef2b865ab05bca8093d4180702fb7f6caecf6b9119013f9d3ebf61e113e71ed"
      url "https://github.com/imagewize/wp-ops/releases/download/v#{version}/wp-ops_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6e5ec9e3e813992102534e18b67ef32bff4d8ff223f5e58c7c84bfd0724fdd65"
      url "https://github.com/imagewize/wp-ops/releases/download/v#{version}/wp-ops_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d8f4ac37442366aeeca89136b7e88ffd9d32b3b03d1ee23136674bbcc37f9e21"
      url "https://github.com/imagewize/wp-ops/releases/download/v#{version}/wp-ops_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b2467f9a15a3bf9c1fb4eb6550178a6a7252f9ef09e5bfc93aa2c970b61bddf3"
      url "https://github.com/imagewize/wp-ops/releases/download/v#{version}/wp-ops_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wp-ops"
  desc "Unified CLI for WordPress operations, Trellis, and Bedrock workflows"
  homepage "https://github.com/imagewize/wp-ops"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wp-ops"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wp-ops"]
    end
  end

  # No zap stanza required

end
