# This file was generated by GoReleaser. DO NOT EDIT.
cask "wp-ops" do
  binary "wp-ops", target: "trellis-ops"

  version "5.23.0"

  on_macos do
    on_arm do
      sha256 "4724813641d5f9d07d6a5f9acc42dafc28c8d234ae922cdff98deea63f6bfa2a"
      url "https://github.com/imagewize/wp-ops/releases/download/v#{version}/wp-ops_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0e2cb7ee3def7b2caaca58bf4ae21edead846c5e42d6b12bee2e13f89f0d54fd"
      url "https://github.com/imagewize/wp-ops/releases/download/v#{version}/wp-ops_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4afac94e5a5446fd84a40e1da66a8eed1af743e4dfa841c18d8df0ac95a2dc55"
      url "https://github.com/imagewize/wp-ops/releases/download/v#{version}/wp-ops_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "be06cd1900ca06f1419f947ebd80159eda25ff159cb2204d41be0b339ab469ae"
      url "https://github.com/imagewize/wp-ops/releases/download/v#{version}/wp-ops_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wp-ops"
  desc "Unified CLI for WordPress operations, Trellis, and Bedrock workflows"
  homepage "https://github.com/imagewize/wp-ops"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wp-ops"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wp-ops"]
    end
  end

  # No zap stanza required
end
